<?php

namespace AHalfWildSheep\iTop\Extension\DashletFeed\Controller;

use Combodo\iTop\Application\UI\Base\Component\Dashlet\DashletContainer;
use Combodo\iTop\Application\UI\Base\tJSRefreshCallback;

class DashletFeedView extends DashletContainer {
	use tJSRefreshCallback;

	public const BLOCK_CODE = 'ahws-dashlet-feed';
	public const DEFAULT_HTML_TEMPLATE_REL_PATH = 'ahws-dashlet-feed/view/DashletFeedView';
	public const DEFAULT_JS_ON_READY_TEMPLATE_REL_PATH = 'ahws-dashlet-feed/view/DashletFeedView';

	private mixed $aActivities;
	private mixed $sTitle;
	private mixed $sClass;

	public function __construct($sId, $sTitle, $aActivities, $sClass) {
		parent::__construct($sId);

		$this->sTitle = $sTitle;
		$this->aActivities = $aActivities;
		$this->sClass = $sClass;
	}

	public function GetSubBlocks(): array
	{
		return $this->aActivities; // TODO: Change the autogenerated stub
	}

	public function GetTitle(): mixed
	{
		return $this->sTitle;
	}

	public function SetTitle(mixed $sTitle): void
	{
		$this->sTitle = $sTitle;
	}

	public function GetClass(): mixed
	{
		return $this->sClass;
	}

	public function SetClass(mixed $sClass): void
	{
		$this->sClass = $sClass;
	}

	public function GetActivities(): mixed
	{
		return $this->aActivities;
	}

	public function SetActivities(array $aActivities): void
	{
		$this->aActivities = $aActivities;
	}

}